# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'accepORders' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for accepORders
pod 'SnapKit'

  target 'accepORdersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'accepORdersUITests' do
    # Pods for testing
  end

end
